language: python
dist: Xenial
python: "3.6"

before_install:
  - export DL_DIR=$HOME/downloads
  - mkdir -p $DL_DIR
  - cd $DL_DIR

  # Install and configure Conda
  - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  # Create Conda environment with required packages
  - conda create -q -n litedram -c 'conda-forge' -c 'litex-hub'
      verilator libevent json-c
      gcc-riscv64-elf-nostdc
  - conda activate litedram

  # Get Migen / LiteX / Cores
  - wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
  - python3 litex_setup.py init install

  # Simulation script dependences
  - pip install pexpect

  # Replace litex' litedram with currently tested revision
  - cd $TRAVIS_BUILD_DIR
  - ./setup.py install -f

script: ./.sim-test.py --sdram-module="$SDRAM_MODULE"

jobs:
  include:
    - stage: "Unit tests"
      script: python setup.py test

    - stage: "Simulations"
      env: SDRAM_MODULE=IS42S16160
    - env: SDRAM_MODULE=IS42S16320
    - env: SDRAM_MODULE=MT48LC4M16
    - env: SDRAM_MODULE=MT48LC16M16
    - env: SDRAM_MODULE=AS4C16M16
    - env: SDRAM_MODULE=AS4C32M16
    - env: SDRAM_MODULE=AS4C32M8
    - env: SDRAM_MODULE=M12L64322A
    - env: SDRAM_MODULE=M12L16161A
    - env: SDRAM_MODULE=MT46V32M16
    - env: SDRAM_MODULE=MT46H32M16
    - env: SDRAM_MODULE=MT46H32M32
    - env: SDRAM_MODULE=MT47H128M8
    - env: SDRAM_MODULE=MT47H32M16
    - env: SDRAM_MODULE=MT47H64M16
    - env: SDRAM_MODULE=P3R1GE4JGF
    - env: SDRAM_MODULE=MT41K64M16
    - env: SDRAM_MODULE=MT41J128M16
    - env: SDRAM_MODULE=MT41J256M16
    - env: SDRAM_MODULE=K4B1G0446F
    - env: SDRAM_MODULE=K4B2G1646F
    - env: SDRAM_MODULE=H5TC4G63CFR
    - env: SDRAM_MODULE=IS43TR16128B
    - env: SDRAM_MODULE=MT8JTF12864
    - env: SDRAM_MODULE=MT8KTF51264
    - env: SDRAM_MODULE=MT18KSF1G72HZ
    - env: SDRAM_MODULE=AS4C256M16D3A
    - env: SDRAM_MODULE=MT16KTF1G64HZ
    - env: SDRAM_MODULE=EDY4016A
    - env: SDRAM_MODULE=MT40A1G8
    - env: SDRAM_MODULE=MT40A512M16

